version: "3"
services:
    web:
        build: .
        ports:
            - "8080:5000"
        # depends_on:
        #     - db
        links:
            - db
        environment:
            SQLSERVER_HOST: "Server=db;Database=Quiztest1DBLinux;User=sa;Password=Your_password123"
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"