version: "2"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        links:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"