version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        # depends_on:
        #     - db
        links:
            - db
        environment:
            SQLSERVER_HOST: "Data Source=db;Initial Catalog=Quiztest1DBLinux;Integrated Security=True;Pooling=False;User Id=sa;Password=Your_password123"
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"